---
stages:
  - build

docker_build:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+.\d+.\d+/
      exists:
        - django/Dockerfile
      when: on_success
    - when: manual
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    - env
    - export
    - echo "Running build with tag $tag"
    - tag=$CI_COMMIT_TAG
    - cd ./django
    - docker build -t sergeyershov/django-app:$tag .
    - docker push sergeyershov/django-app:$tag