---
stages:
  - build

docker_build:
  stage: build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    - cd ./django
    - docker build -t sergeyershov/django-app:$CI_COMMIT_TAG .
    - docker push sergeyershov/django-app:$CI_COMMIT_TAG
  rules:
    - if: $CI_COMMIT_BRANCH == 'main' && $CI_COMMIT_TAG != null