---
stages:
  - build

docker_build:
  stage: build
  rules:
    - if: '$CI_COMMIT_TAG'
      changes:
        - django/Dockerfile
      when: on_success
    - when: manual
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    - cd ./django
    - docker build -t sergeyershov/django-app:$CI_COMMIT_TAG .
    - docker push sergeyershov/django-app:$CI_COMMIT_TAG