---
stages:
  - build
  - deploy

docker_build:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+.\d+.\d+/
      exists:
        - django/Dockerfile
      when: on_success
    - when: manual
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    - env
    - export
    - tag=$CI_COMMIT_TAG
    - echo "Running build with tag $tag"
    - cd ./django
    - docker build -t sergeyershov/django-app:$tag .
    - docker push sergeyershov/django-app:$tag

app_deploy: 
  stage: deploy
  environment: production
  script:
    - tag=$CI_COMMIT_TAG
    - echo "Deploy app with build version $tag"
    - helm upgrade --atomic --timeout 600s --set myapp.tag=$tag --install --namespace $CI_K8S_NAMESPACE myapp https://gitlab.com/sf-devops32/fs-summury/-/tree/main/kube/myapp/chart
    - kubectl get pods -n $CI_K8S_NAMESPACE
   