apiVersion: v1
kind: Service
metadata:
  name: django
  labels:
    app: django
spec:
  type: LoadBalancer
  ports:
    - port: 3003 
      targetPort: 3003
  externalIPs:
    - 10.128.0.35
    - 10.128.0.21
  selector:
    name:  django